In [2]:
import pandas as pd

In [2]:
df_2018 = pd.read_csv("openpv-export-201808201545.csv")

In [3]:
df_2018.head()

,state,date_installed,incentive_prog_names,type,size_kw,appraised,zipcode,install_type,installer,cost_per_watt,...,effic_1,cust_county,tracking,inv_model_clean,mod_cost_real,inv_cost_real,bos_powerclerk_real,permitting_real,3rdparty,Filters=maxdate=1534723200&mindate=1514764800
0,TX,01/03/2018,NaN,uir,5.775,NaN,76034,Residential,Axium Solar,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PA,01/10/2018,NaN,uir,10.890,NaN,19335,Residential,Paradise Energy Solutions LLC,2.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VA,01/12/2018,NaN,uir,9.570,NaN,22802,Residential,Paradise Energy Solutions LLC,2.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NY,01/15/2018,NaN,uir,15.180,NaN,14551,Residential,Paradise Energy Solutions LLC,3.12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MD,01/26/2018,NaN,uir,66.660,NaN,21218,Commercial,Paradise Energy Solutions LLC,4.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_2018.shape

(77, 82)

In [6]:
df_2018.columns

Index(['state', 'date_installed', 'incentive_prog_names', 'type', 'size_kw',
       'appraised', 'zipcode', 'install_type', 'installer', 'cost_per_watt',
       'cost', 'lbnl_tts_version_year', 'lbnl_tts', 'city', 'utility_clean',
       'tech_1', 'model1_clean', 'county', 'annual_PV_prod',
       'annual_insolation', 'rebate', 'sales_tax_cost', 'tilt1',
       'tracking_type', 'azimuth1', 'manuf2_clean', 'manuf3_clean',
       'manuf1_clean', 'inv_man_clean', 'reported_annual_energy_prod',
       'incentivetype', 'year_app_implied', 'year', 'npv_fit_real',
       'application_implied', 'npv_pbi_real', 'other_incentive',
       'appraised_cluster', 'inflation', 'other_incentive_real',
       'zip_available', 'cust_city', 'pbi', 'pbi_real', 'pbi_length',
       'application', 'fit_length', 'fit_rate', 'fit_payment',
       '_3rdparty_implied', 'utility', 'install_price_real_w', 'install_price',
       'installer_clean', 'manuf1_', 'inverter_reported', 'rebate_real',
       'model1', '_3rdparty', 'inv_model_reported', 'microinv_solarhub',
       'bipv_3', 'bipv_2', 'bipv_1', 'sales_tax_rate', 'sales_tax_cost_real',
       'bipv_all', 'thinfilm_all', 'china', 'sys_sizeac', 'pbi_rate',
       'new_constr', 'effic_1', 'cust_county', 'tracking', 'inv_model_clean',
       'mod_cost_real', 'inv_cost_real', 'bos_powerclerk_real',
       'permitting_real', '3rdparty',
       'Filters=maxdate=1534723200&mindate=1514764800'],
      dtype='object')

In [7]:
df_2017 = pd.read_csv("openpv-2017.csv")

In [8]:
df_2017.shape

(329, 82)

In [9]:
df_2017.head()

,state,date_installed,incentive_prog_names,type,size_kw,appraised,zipcode,install_type,installer,cost_per_watt,...,effic_1,cust_county,tracking,inv_model_clean,mod_cost_real,inv_cost_real,bos_powerclerk_real,permitting_real,3rdparty,Filters=maxdate=1514678400&mindate=1483228800
0,OK,01/01/2017,NaN,uir,7.20,NaN,74055,Residential,NaN,5.42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AL,01/04/2017,NaN,uir,3000.00,NaN,36912,Commercial,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TX,01/06/2017,NaN,uir,1111.59,NaN,75211,Commercial,Axium Solar,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NY,01/06/2017,NaN,uir,16.12,NaN,13041,Residential,Paradise Energy Solutions,3.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PA,01/06/2017,NaN,uir,89.28,NaN,17406,Commercial,Paradise EnergySolutions,2.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_2017.install_type.value_counts()

Residential     226
Commercial       60
Agricultural     35
Government        5
Unknown           1
Nonprofit         1
Educational       1
Name: install_type, dtype: int64

In [3]:
# SEIA residential solar installations
residential = pd.read_excel("SEIA Resi data by state.xlsx", skiprows=1)

In [5]:
residential.shape

(46, 12)